---

# https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx

- name: add certbot (letsencrypt) repo
  become: yes
  apt_repository: repo="ppa:certbot/certbot"

- name: install nginx packages
  become: yes
  apt: name="python-certbot-nginx"
  notify: restart nginx
